version: '3'
services:
  db:
    image: mysql:latest
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=''
    volumes:
      - ./.db/var/lib/mysql:/var/lib/mysql
      - ./temp/app/mysqld:/var/run/mysqld
    restart: unless-stopped

  web:
    image: django:latest
    env_file:
      - ./.env
    command: python /app/myproject/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./temp/app/mysqld:/var/run/mysqld
    restart: always
    depends_on:
      db:
        condition: service_started