# Generated by Django 4.1.6 on 2023-02-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_name_booking_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
